version: '3.8'
services:
  redis-replica:
    image: redis:7.4-alpine
    container_name: redis-replica
    restart: always
    network_mode: host
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - redis-data:/data
    command: redis-server /usr/local/etc/redis/redis.conf

volumes:
  redis-data: