version: '3.8'

services:
  redis-2:
    image: redis:7.4-alpine
    container_name: redis-2
    restart: always
    network_mode: host  # 同樣走高效率 host 網路
    environment:
      - REDIS_PASSWORD=${REDIS_PASS}
    command: >
      redis-server
      --port 6379
      --bind 0.0.0.0
      --protected-mode no
      --requirepass ${REDIS_PASS:-MyDefaultPasswordDoNotUse}
      --masterauth ${REDIS_PASS:-MyDefaultPasswordDoNotUse}
      --appendonly yes
      --maxclients 10000
      --replicaof 172.17.0.3 6379  # 🟢 關鍵：填入剛剛查到的 lab-node-1 IP