version: '3.8'

services:
  redis-cluster-node:
    image: redis:7.4-alpine
    container_name: ${REDIS_CONTAINER_NAME}
    restart: always
    network_mode: host
    environment:
      - REDIS_PASSWORD=${REDIS_PASS}
    command: >
      redis-server
      --port ${REDIS_PORT}
      --bind 0.0.0.0
      --protected-mode no
      --requirepass ${REDIS_PASS}
      --masterauth ${REDIS_PASS}
      --appendonly yes
      --cluster-enabled yes
      --cluster-config-file nodes.conf
      --cluster-node-timeout 5000
      --cluster-announce-ip ${MY_HOST_IP}
      --cluster-announce-port ${REDIS_PORT}
      --cluster-announce-bus-port ${REDIS_BUS_PORT}